// Generated by CoffeeScript 1.10.0
(function() {
  var LeaveEvent, _function, async, authorizeApp, calendar, fellowsLeaveCalendarId;

  async = require('async');

  LeaveEvent = require('../userdb').LeaveEvent;

  authorizeApp = require('../googleApi').authorizeApp;

  calendar = require('googleapis').calendar('v3');

  fellowsLeaveCalendarId = 'andela.co_8q5ndpq7vfikvmrinv0oladgd8@group.calendar.google.com';

  async.waterfall([
    function(callback) {
      authorizeApp(function(authClient) {
        return callback(null, authClient);
      });
    }, function(auth, callback) {
      calendar.events.list({
        auth: auth,
        calendarId: fellowsLeaveCalendarId,
        timeMin: '2015-11-01T11:06:33+00:00',
        timeMax: '2015-12-30T11:06:33+00:00'
      }, function(err, all) {
        if (err) {
          console.log("There was an error contacting the Calendar service: " + err);
        }
        if (all) {
          return callback(null, all.items);
        }
      });
    }, function(events, callback) {
      console.log(events[0]);
      callback(null, 'done');
    }
  ], function(err, result) {
    console.log(result);
    process.exit(1);
  });

  _function = function(leaveEvents) {
    return async.each(leaveEvents, (function(event, callback) {
      console.log('Processing file ');
      if (event) {
        console.log('This file name is too long');
        callback();
      }
    }));
  };

}).call(this);
